{% set name = "net-van" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/huh-uh/net-van.git


requirements:
  host:
    - colorama   # [ win ]
    - importlib-metadata   # [ py < 38 ]
    - pip
    - python

  run:
    - colorama   # [ win ]
    - importlib-metadata   # [ py < 38 ]
    - python
    - numpy

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Small and easy to use feed-forward ANN library."

extra:
  maintainers:
    - Vavrinec Kavan
