[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "net-van"
version = "0.0.1"
authors = [
  { name="Vavrinec Kavan", email="vavrinec.kavan@gmail.com" },
]
description = "A small and easy to use feed-forward ANN library"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/huh-uh/net-van"